-- Create Database
create database auction
go

--Using Database
use auction
go

-- Table: USER
CREATE TABLE [USER] (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_NAME NVARCHAR(100),
    EMAIL NVARCHAR(255) UNIQUE NOT NULL,
    PHONE NVARCHAR(20),
    PASSWORD NVARCHAR(255) NOT NULL,
    EMAIL_ACTIVATION BIT,
    BUYER_ACTIVATION BIT,
    SELLER_ACTIVATION BIT,
    DISPLAY_USERNAME NVARCHAR(50),
    COUNTRY NVARCHAR(100),
    GOV NVARCHAR(100),
    CITY NVARCHAR(100),
    ADDRESS NVARCHAR(255),
    INLAND BIT,
    FULL_ID_NAME NVARCHAR(255),
    ID_NO NVARCHAR(50),
    ID_PHOTO VARBINARY(MAX),
    BANK_NAME NVARCHAR(100),
    IBAN NVARCHAR(50),
    BALANCE DECIMAL(18, 2) DEFAULT 0.00,
    LOYALTY_POINTS INT DEFAULT 0,
    DIS_CODE NVARCHAR(20)
);

-- Table: CATEGORY
CREATE TABLE CATEGORY (
    CAT_ID INT IDENTITY(1,1) PRIMARY KEY,
    CAT_NAME NVARCHAR(100) NOT NULL
);

-- Table: ITEM
CREATE TABLE ITEM (
    I_ID INT IDENTITY(1,1) PRIMARY KEY,
    ITEM_NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(MAX),
    PHOTO VARBINARY(MAX),
    STARTING_PRICE DECIMAL(18, 2),
    EXPECTED_PRICE DECIMAL(18, 2),
    LOCATION NVARCHAR(255),
    START_DATE DATE,
    DELIVERED_DATE DATE,
    PERIOD_OF_BID INT,
    STATUS NVARCHAR(50),
    SHIP_PRICE DECIMAL(18, 2),
    SHIP_DATE DATE,
    ARRIVAL_DATE DATE,
    CAT_ID INT,
    POST_BY INT,
    SHIPD_BY INT,
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID),
    FOREIGN KEY (POST_BY) REFERENCES [USER](USER_ID),
    FOREIGN KEY (SHIPD_BY) REFERENCES [USER](USER_ID)
);

-- Table: BIDS
CREATE TABLE BIDS (
    BID_ID INT IDENTITY(1,1) PRIMARY KEY,
    BID_AMOUNT DECIMAL(18, 2),
    BID_TIME DATETIME,
    WIN_STATUS BIT,
    BIDDER_ID INT,
    I_ID INT,
    FOREIGN KEY (BIDDER_ID) REFERENCES [USER](USER_ID),
    FOREIGN KEY (I_ID) REFERENCES ITEM(I_ID)
);

-- Table: FEEDBACK
CREATE TABLE FEEDBACK (
    FEEDBACK_ID INT IDENTITY(1,1) PRIMARY KEY,
    DATE DATE,
    RATING INT CHECK (RATING BETWEEN 1 AND 5),
    COMMENT NVARCHAR(MAX),
    BUYER_ID INT,
    SELLER_ID INT,
    FOREIGN KEY (BUYER_ID) REFERENCES [USER](USER_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES [USER](USER_ID)
);
